#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# 配置指南: https://hexo.fluid-dev.com/docs/guide/
# 你可以从指南中获得更详细的说明
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------


#---------------------------
# 全局
# Global
#---------------------------

# 用于浏览器标签的图标
# Icon for browser tab
favicon: https://avatars.githubusercontent.com/FredBill1

# 用于苹果设备的图标
# Icon for Apple touch
apple_touch_icon: https://avatars.githubusercontent.com/FredBill1

# 强制所有链接升级为 HTTPS（适用于图片等资源出现 HTTP 混入报错）
# Force all links to be HTTPS (applicable to HTTP mixed error)
force_https: true


# 代码块的增强配置
# Enhancements to code blocks
code:
  # 代码高亮
  # Code highlight
  highlight:
    highlightjs:
      # 在链接中挑选 style 填入
      # Select a style in the link
      # See: https://highlightjs.org/static/demo/
      style: "github"
      style_dark: "github-dark"

# 一些好玩的功能
# Some fun features
fun_features:
  # 为 subtitle 添加打字机效果
  # Typing animation for subtitle
  typing:
    enable: false

# 主题颜色配置，其他不生效的地方请使用自定义 css 解决，配色可以在下方链接中获得启发
# Theme color, please use custom CSS to solve other colors, color schema can be inspired by the links below
# See: https://www.webdesignrankings.com/resources/lolcolors/
color:
  # 顶部菜单字体色
  # Color of navigation bar text
  navbar_text_color_dark: "#fff"

  # 副标题字体色
  # Color of navigation bar text
  subtitle_color_dark: "#fff"

# 主题暗色模式，开启后菜单中会出现切换按钮，用户浏览器会存储切换选项，并且会遵循 prefers-color-scheme 自动切换
# Theme dark mode. If enable, a switch button will appear on the menu, each of the visitor's browser will store his switch option
dark_mode:
  # 默认的选项（当用户手动切换后则不再按照默认模式），选择 `auto` 会优先遵循 prefers-color-scheme，其次按用户本地时间 18 点到次日 6 点之间进入暗色模式
  # Default option (when the visitor switches manually, the default mode is no longer followed), choosing `auto` will give priority to prefers-color-scheme, and then enter the dark mode from 18:00 to 6:00 in the visitor’s local time
  # Options: auto | light | dark
  default: dark

# 指定自定义 .js 文件路径，支持列表；路径是相对 source 目录，如 /js/custom.js 对应存放目录 source/js/custom.js
# Specify the path of your custom js file, support list. The path is relative to the source directory, such as `/js/custom.js` corresponding to the directory `source/js/custom.js`
custom_js: 
  - //cdnjs.cloudflare.com/ajax/libs/animejs/2.2.0/anime.min.js
  - /js/cursor-effect.js
  - /js/banner-text-no-warp.js

# 指定自定义 .css 文件路径，用法和 custom_js 相同
# The usage is the same as custom_js
custom_css:
  - /css/banner-text-no-warp.css

# 对页面中的图片和评论插件进行懒加载处理，可见范围外的元素不会提前加载
# Lazy loading of images and comment plugin on the page
lazyload:
  # 加载时的占位图片
  # The placeholder image when loading
  loading_img: /img/loading.svg

#---------------------------
# 页头
# Header
#---------------------------

# 导航栏的相关配置
# Navigation bar
navbar:
  # 导航栏左侧的标题，为空则按 hexo config 中 `title` 显示
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title:


# 首屏图片的相关配置
# Config of the big image on the first screen
banner:
  # 图片最小的宽高比，以免图片两边被过度裁剪，适用于移动端竖屏时，如需关闭设为 0
  # Minimum ratio of width to height, applicable to the vertical screen of mobile device, if you need to close it, set it to 0
  width_height_ratio: 0


#---------------------------
# 首页
# Home Page
#---------------------------
index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/background.png

  # 头图黑色蒙版的不透明度，available: 0 - 1.0， 1 是完全不透明
  # Opacity of the banner mask, 1.0 is completely opaque
  # Available: 0 - 1.0
  banner_mask_alpha: 0

  slogan:
    # 为空则按 hexo config.subtitle 显示
    # If empty, text based on `subtitle` in hexo config
    text:


#---------------------------
# 文章页
# Post Page
#---------------------------
post:
  banner_img: /img/background.png
  banner_img_height: 55
  banner_mask_alpha: 0

  comments:
    enable: true
    # 指定的插件，需要同时设置对应插件的必要参数
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus | discuss
    type: giscus


#---------------------------
# 评论插件
# Comment plugins
#
# 开启评论需要先设置上方 `post: comments: enable: true`，然后根据 `type` 设置下方对应的评论插件参数
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------

# Giscus
# 基于 GitHub Discussions，类似于 Utterances
# Based on GitHub Discussions, similar to Utterances
# See: https://giscus.app/
giscus:
  repo: FredBill1/FredBill1.github.io
  repo-id: R_kgDOKsKEdA
  category: General
  category-id: DIC_kwDOKsKEdM4Ca4I6
  theme: preferred_color_scheme
  mapping: pathname
  strict: 1
  reactions-enabled: 1
  emit-metadata: 0
  input-position: bottom
  lang: zh-CN
  loading: lazy

#---------------------------
# 归档页
# Archive Page
#---------------------------
archive:
  banner_img_height: 55
  banner_img: /img/background.png
  banner_mask_alpha: 0


#---------------------------
# 分类页
# Category Page
#---------------------------
category:
  banner_img_height: 55
  banner_img: /img/background.png
  banner_mask_alpha: 0


#---------------------------
# 标签页
# Tag Page
#---------------------------
tag:
  banner_img_height: 55
  banner_img: /img/background.png
  banner_mask_alpha: 0


#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 55
  banner_mask_alpha: 0
  avatar: https://avatars.githubusercontent.com/FredBill1
  name: FredBill
  intro: ᗜˬᗜ
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/FredBill1", tip: "GitHub" }


#---------------------------
# 自定义页
# Custom Page
#
# 通过 hexo new page 命令创建的页面
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img_height: 55
  banner_img: /img/background.png
  banner_mask_alpha: 0


#---------------------------
# 404页
# 404 Page
#---------------------------
page404:
  banner_img: /img/background.png
  banner_mask_alpha: 0


#---------------------------
# 友链页
# Links Page
#---------------------------
links:
  banner_img_height: 55
  banner_img: /img/background.png
  banner_mask_alpha: 0
