#---------------------------
# é¡µå¤´
# Header
#---------------------------

# å¯¼èˆªæ çš„ç›¸å…³é…ç½®
# Navigation bar
navbar:
  # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config ä¸­ `title` æ˜¾ç¤º
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title:


#---------------------------
# é¦–é¡µ
# Home Page
#---------------------------
index:
  # é¦–é¡µ Banner å¤´å›¾ï¼Œå¯ä»¥æ˜¯ç›¸å¯¹è·¯å¾„æˆ–ç»å¯¹è·¯å¾„ï¼Œä»¥ä¸‹ç›¸åŒ
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/background.png

  slogan:
    # ä¸ºç©ºåˆ™æŒ‰ hexo config.subtitle æ˜¾ç¤º
    # If empty, text based on `subtitle` in hexo config
    text:


#---------------------------
# æ–‡ç« é¡µ
# Post Page
#---------------------------
post:
  banner_img: /img/background.png


#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
  banner_img: /img/background.png


#---------------------------
# åˆ†ç±»é¡µ
# Category Page
#---------------------------
category:
  banner_img: /img/background.png


#---------------------------
# æ ‡ç­¾é¡µ
# Tag Page
#---------------------------
tag:
  enable: true
  banner_img: /img/background.png


#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: https://avatars.githubusercontent.com/FredBill1
  name: FredBill
  intro: ğŸ˜‹
  # æ›´å¤šå›¾æ ‡å¯ä» https://hexo.fluid-dev.com/docs/icon/ æŸ¥æ‰¾ï¼Œ`class` ä»£è¡¨å›¾æ ‡çš„ css classï¼Œæ·»åŠ  `qrcode` åï¼Œå›¾æ ‡ä¸å†æ˜¯é“¾æ¥è€Œæ˜¯æ‚¬æµ®äºŒç»´ç 
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/FredBill1", tip: "GitHub" }


#---------------------------
# è‡ªå®šä¹‰é¡µ
# Custom Page
#
# é€šè¿‡ hexo new page å‘½ä»¤åˆ›å»ºçš„é¡µé¢
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img: /img/background.png


#---------------------------
# 404é¡µ
# 404 Page
#---------------------------
page404:
  banner_img: /img/background.png


#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
  enable: true
  banner_img: /img/background.png