#---------------------------
# Hexo Theme Fluid
# Author: Fluid-dev
# Github: https://github.com/fluid-dev/hexo-theme-fluid
#
# é…ç½®æŒ‡å—: https://hexo.fluid-dev.com/docs/guide/
# ä½ å¯ä»¥ä»æŒ‡å—ä¸­è·å¾—æ›´è¯¦ç»†çš„è¯´æ˜
#
# Guide: https://hexo.fluid-dev.com/docs/en/guide/
# You can get more detailed help from the guide
#---------------------------


#---------------------------
# å…¨å±€
# Global
#---------------------------

# ç”¨äºæµè§ˆå™¨æ ‡ç­¾çš„å›¾æ ‡
# Icon for browser tab
favicon: https://avatars.githubusercontent.com/FredBill1

# ç”¨äºè‹¹æœè®¾å¤‡çš„å›¾æ ‡
# Icon for Apple touch
apple_touch_icon: https://avatars.githubusercontent.com/FredBill1

# å¼ºåˆ¶æ‰€æœ‰é“¾æ¥å‡çº§ä¸º HTTPSï¼ˆé€‚ç”¨äºå›¾ç‰‡ç­‰èµ„æºå‡ºç° HTTP æ··å…¥æŠ¥é”™ï¼‰
# Force all links to be HTTPS (applicable to HTTP mixed error)
force_https: true

# ä¸€äº›å¥½ç©çš„åŠŸèƒ½
# Some fun features
fun_features:
  # ä¸º subtitle æ·»åŠ æ‰“å­—æœºæ•ˆæœ
  # Typing animation for subtitle
  typing:
    enable: false


# ä¸»é¢˜æš—è‰²æ¨¡å¼ï¼Œå¼€å¯åèœå•ä¸­ä¼šå‡ºç°åˆ‡æ¢æŒ‰é’®ï¼Œç”¨æˆ·æµè§ˆå™¨ä¼šå­˜å‚¨åˆ‡æ¢é€‰é¡¹ï¼Œå¹¶ä¸”ä¼šéµå¾ª prefers-color-scheme è‡ªåŠ¨åˆ‡æ¢
# Theme dark mode. If enable, a switch button will appear on the menu, each of the visitor's browser will store his switch option
dark_mode:
  # é»˜è®¤çš„é€‰é¡¹ï¼ˆå½“ç”¨æˆ·æ‰‹åŠ¨åˆ‡æ¢ååˆ™ä¸å†æŒ‰ç…§é»˜è®¤æ¨¡å¼ï¼‰ï¼Œé€‰æ‹© `auto` ä¼šä¼˜å…ˆéµå¾ª prefers-color-schemeï¼Œå…¶æ¬¡æŒ‰ç”¨æˆ·æœ¬åœ°æ—¶é—´ 18 ç‚¹åˆ°æ¬¡æ—¥ 6 ç‚¹ä¹‹é—´è¿›å…¥æš—è‰²æ¨¡å¼
  # Default option (when the visitor switches manually, the default mode is no longer followed), choosing `auto` will give priority to prefers-color-scheme, and then enter the dark mode from 18:00 to 6:00 in the visitorâ€™s local time
  # Options: auto | light | dark
  default: dark


#---------------------------
# é¡µå¤´
# Header
#---------------------------

# å¯¼èˆªæ çš„ç›¸å…³é…ç½®
# Navigation bar
navbar:
  # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config ä¸­ `title` æ˜¾ç¤º
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title:


# é¦–å±å›¾ç‰‡çš„ç›¸å…³é…ç½®
# Config of the big image on the first screen
banner:
  # å›¾ç‰‡æœ€å°çš„å®½é«˜æ¯”ï¼Œä»¥å…å›¾ç‰‡ä¸¤è¾¹è¢«è¿‡åº¦è£å‰ªï¼Œé€‚ç”¨äºç§»åŠ¨ç«¯ç«–å±æ—¶ï¼Œå¦‚éœ€å…³é—­è®¾ä¸º 0
  # Minimum ratio of width to height, applicable to the vertical screen of mobile device, if you need to close it, set it to 0
  width_height_ratio: 0


#---------------------------
# é¦–é¡µ
# Home Page
#---------------------------
index:
  # é¦–é¡µ Banner å¤´å›¾ï¼Œå¯ä»¥æ˜¯ç›¸å¯¹è·¯å¾„æˆ–ç»å¯¹è·¯å¾„ï¼Œä»¥ä¸‹ç›¸åŒ
  # Path of Banner image, can be a relative path or an absolute path, the same on other pages
  banner_img: /img/background.png

  slogan:
    # ä¸ºç©ºåˆ™æŒ‰ hexo config.subtitle æ˜¾ç¤º
    # If empty, text based on `subtitle` in hexo config
    text:


#---------------------------
# æ–‡ç« é¡µ
# Post Page
#---------------------------
post:
  banner_img: /img/background.png
  banner_img_height: 55

  comments:
    enable: true
    # æŒ‡å®šçš„æ’ä»¶ï¼Œéœ€è¦åŒæ—¶è®¾ç½®å¯¹åº”æ’ä»¶çš„å¿…è¦å‚æ•°
    # The specified plugin needs to set the necessary parameters at the same time
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis | giscus | discuss
    type: giscus


#---------------------------
# è¯„è®ºæ’ä»¶
# Comment plugins
#
# å¼€å¯è¯„è®ºéœ€è¦å…ˆè®¾ç½®ä¸Šæ–¹ `post: comments: enable: true`ï¼Œç„¶åæ ¹æ® `type` è®¾ç½®ä¸‹æ–¹å¯¹åº”çš„è¯„è®ºæ’ä»¶å‚æ•°
# Enable comments need to be set `post: comments: enable: true`, then set the corresponding comment plugin parameters below according to `type`
#---------------------------

# Giscus
# åŸºäº GitHub Discussionsï¼Œç±»ä¼¼äº Utterances
# Based on GitHub Discussions, similar to Utterances
# See: https://giscus.app/
giscus:
  repo: FredBill1/FredBill1.github.io
  repo-id: R_kgDOKsKEdA
  category: General
  category-id: DIC_kwDOKsKEdM4Ca4I6
  theme: preferred_color_scheme
  mapping: pathname
  strict: 1
  reactions-enabled: 1
  emit-metadata: 0
  input-position: bottom
  lang: zh-CN
  loading: lazy

#---------------------------
# å½’æ¡£é¡µ
# Archive Page
#---------------------------
archive:
  banner_img_height: 55
  banner_img: /img/background.png


#---------------------------
# åˆ†ç±»é¡µ
# Category Page
#---------------------------
category:
  banner_img_height: 55
  banner_img: /img/background.png


#---------------------------
# æ ‡ç­¾é¡µ
# Tag Page
#---------------------------
tag:
  banner_img_height: 55
  banner_img: /img/background.png


#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/background.png
  banner_img_height: 55
  banner_mask_alpha: 0.3
  avatar: https://avatars.githubusercontent.com/FredBill1
  name: FredBill
  intro: ğŸ˜‹
  # æ›´å¤šå›¾æ ‡å¯ä» https://hexo.fluid-dev.com/docs/icon/ æŸ¥æ‰¾ï¼Œ`class` ä»£è¡¨å›¾æ ‡çš„ css classï¼Œæ·»åŠ  `qrcode` åï¼Œå›¾æ ‡ä¸å†æ˜¯é“¾æ¥è€Œæ˜¯æ‚¬æµ®äºŒç»´ç 
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/FredBill1", tip: "GitHub" }


#---------------------------
# è‡ªå®šä¹‰é¡µ
# Custom Page
#
# é€šè¿‡ hexo new page å‘½ä»¤åˆ›å»ºçš„é¡µé¢
# Custom Page through `hexo new page`
#---------------------------
page:
  banner_img_height: 55
  banner_img: /img/background.png


#---------------------------
# 404é¡µ
# 404 Page
#---------------------------
page404:
  banner_img: /img/background.png


#---------------------------
# å‹é“¾é¡µ
# Links Page
#---------------------------
links:
  banner_img_height: 55
  banner_img: /img/background.png