#---------------------------
# é¡µå¤´
# Header
#---------------------------

# å¯¼èˆªæ çš„ç›¸å…³é…ç½®
# Navigation bar
navbar:
  # å¯¼èˆªæ å·¦ä¾§çš„æ ‡é¢˜ï¼Œä¸ºç©ºåˆ™æŒ‰ hexo config ä¸­ `title` æ˜¾ç¤º
  # The title on the left side of the navigation bar. If empty, it is based on `title` in hexo config
  blog_title:


#---------------------------
# é¦–é¡µ
# Home Page
#---------------------------
index:
  slogan:
    # ä¸ºç©ºåˆ™æŒ‰ hexo config.subtitle æ˜¾ç¤º
    # If empty, text based on `subtitle` in hexo config
    text:

#---------------------------
# å…³äºé¡µ
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: https://avatars.githubusercontent.com/FredBill1
  name: FredBill
  intro: ğŸ˜‹
  # æ›´å¤šå›¾æ ‡å¯ä» https://hexo.fluid-dev.com/docs/icon/ æŸ¥æ‰¾ï¼Œ`class` ä»£è¡¨å›¾æ ‡çš„ css classï¼Œæ·»åŠ  `qrcode` åï¼Œå›¾æ ‡ä¸å†æ˜¯é“¾æ¥è€Œæ˜¯æ‚¬æµ®äºŒç»´ç 
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/FredBill1", tip: "GitHub" }